from datetime import date
from io import BytesIO

from fastapi import HTTPException
from fastapi.responses import StreamingResponse


def validate_date_range(start_date: date, end_date: date) -> None:
    """Apply the shared safety limits used by every date-based report."""
    if end_date < start_date:
        raise HTTPException(
            status_code=400,
            detail="End date must be on or after start date",
        )
    if (end_date - start_date).days > 370:
        raise HTTPException(status_code=400, detail="Date ranges cannot exceed 370 days")


def attachment_response(
    content: bytes,
    filename: str,
    media_type: str,
    extra_headers: dict[str, str] | None = None,
) -> StreamingResponse:
    """Return generated bytes as a browser download with a safe filename."""
    headers = {"Content-Disposition": f'attachment; filename="{filename}"'}
    headers.update(extra_headers or {})
    return StreamingResponse(
        BytesIO(content),
        media_type=media_type,
        headers=headers,
    )
